version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_ENDPOINT}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TAG=${COMMIT_HASH}
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
      - LATEST_IMAGE_URI="${REPOSITORY_URI}:latest"
  build:
    commands:
      - |
        docker build \
          -t "$IMAGE_URI" \
          -t "$LATEST_IMAGE_URI" .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - docker push "$LATEST_IMAGE_URI"
      - printf '[{"name":"%s","imageUri":"%s"}]' "$APP_NAME" "$IMAGE_URI" > images.json
artifacts:
  files: images.json
