AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 instance


Parameters:

  EC2InstanceAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  
  Subnet:
    Type: AWS::EC2::Subnet::Id
  
  VPC:
    Type: AWS::EC2::VPC::Id
  
  GitHubBranch:
    Type: String
    Default: main

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref EC2InstanceAMI
      InstanceType: t3.micro
      SubnetId: !Ref Subnet
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64:
          !Sub
            - |
              #!/bin/bash
              yum update -y
              yum install -y git
              yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
              yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
              git clone https://github.com/soluzionifutura/unimore-ecs.git /var/myapp
              cd /var/myapp
              git checkout ${GitHubBranch}
              nohup node index.js
            - GitHubBranch: !Ref GitHubBranch
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}
        - Key: Environment
          Value: sandbox

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access on port 3000
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole